name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      MANAGER_TAG: "1.9.3-beta.0"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev build-essential
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Deploy manager contracts and run MySQL container
      run: |
        #
        bash ./scripts/create_environment.sh
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python tests/prepare_validator.py
        ENV=DEV py.test -v -s --cov=./ tests/ --cov-report term-missing
    - name: Codecov
      run: |
        codecov -t $CODECOV_TOKEN
