name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install python dependencies
        run: uv sync --all-extras --prerelease=allow

      - name: Checking formatting with ruff
        run: uv run ruff check

      - name: Type check with mypy
        run: uv run mypy .

      - name: Export env
        run: |
          . ./scripts/export_env.sh
          printenv >> $GITHUB_ENV

      - name: Deploy skale manager
        run: |
          export ETH_PRIVATE_KEY=$(cat helper-scripts/private_key.txt)
          bash helper-scripts/deploy_manager.sh

      - name: Run tests
        run: bash scripts/run_tests.sh

      - name: Codecov
        run: |
          uv run codecov -t $CODECOV_TOKEN
